#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
    path: /
    controller: App\Controller\IndexController::index
connexion:
    path: /connexion
    controller: App\Controller\ConnexionController::index
inscription:
    path: /inscription
    controller: App\Controller\InscriptionController::index
inscriptionAction:
    path: /ajax/inscriptionAction
    controller: App\Controller\InscriptionController::inscriptionAction
user:
    path: /user/{id}
    controller: App\Controller\UserController::index
article:
    path: /article
    controller: App\Controller\ArticleController::index
articleShow:
    path: /article/{id}
    controller: App\Controller\ArticleController::show
contact:
    path: /contact
    controller: App\Controller\ContactController::index
contactSendMessage:
    path: /ajax/contact/sendMessage
    controller: App\Controller\ContactController::sendMessage
restaurants:
    path: /restaurants
    controller: App\Controller\RestaurantController::index