#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
  path: /
  controller: App\Controller\IndexController::index
connexion:
  path: /connexion
  controller: App\Controller\ConnexionController::index
connexionAction:
  path: /ajax/connexionAction
  controller: App\Controller\ConnexionController::connexionAction
inscription:
  path: /inscription
  controller: App\Controller\InscriptionController::index
inscriptionAction:
  path: /ajax/inscriptionAction
  controller: App\Controller\InscriptionController::inscriptionAction
user:
  path: /user/{id}
  controller: App\Controller\UserController::index
article:
  path: /article
  controller: App\Controller\ArticleController::index
articleShow:
  path: /article/{id}
  controller: App\Controller\ArticleController::show
storeShow:
  path: /store/{id}
  controller: App\Controller\StoreController::show
contact:
  path: /contact
  controller: App\Controller\ContactController::index
contactSendMessage:
  path: /ajax/contact/sendMessage
  controller: App\Controller\ContactController::sendMessage
restaurants:
  path: /restaurants
  controller: App\Controller\RestaurantController::index
meal:
  path: /meal
  controller: App\Controller\MealController::index
stores:
  path: /stores
  controller: App\Controller\StoreController::index
devenirVegetarien:
  path: /devenirvegetarien
  controller: App\Controller\DevenirVegetarienController::index
blog:
  path: /blog
  controller: App\Controller\BlogController::index
PasswordForgot:
  path: /PasswordForgot
  controller: App\Controller\PasswordForgotController::index
passwordForgot:
  path: /ajax/passwordForgot
  controller: App\Controller\PasswordForgotController::PasswordForgotAjax
passwordForgotChange:
  path: /ajax/passwordForgotChange
  controller: App\Controller\PasswordForgotController::passwordForgotChange
deconnexion:
  path: /deconnexion
  controller: App\Controller\ConnexionController::logout
admin:
  path: /admin
  controller: App\Controller\AdminController::index
adminManagementArticles:
  path: /admin/ManagementArticles
  controller: App\Controller\Admin\ManagementArticlesController::managementArticles
adminManagementArticlesComments:
  path: /admin/ManagementArticlesComments
  controller: App\Controller\Admin\ManagementArticlesController::managementArticlesComments
adminManagementStores:
  path: /admin/ManagementStores
  controller: App\Controller\Admin\ManagementStoresController::managementStores
adminManagementProductsStores:
  path: /admin/ManagementProductsStores
  controller: App\Controller\Admin\ManagementStoresController::managementProductsStores
adminManagementRestaurants:
  path: /admin/ManagementRestaurants
  controller: App\Controller\Admin\ManagementRestaurantsController::managementRestaurants
adminManagementRestaurantsFeedback:
  path: /admin/ManagementRestaurantsFeedback
  controller: App\Controller\Admin\ManagementRestaurantsController::managementRestaurantsFeedback
adminProducts:
  path: /admin/products
  controller: App\Controller\Admin\ManagementProductsController::products
adminUsers:
  path: /admin/users
  controller: App\Controller\Admin\ManagementUsersController::users
adminMeal:
  path: /admin/meal
  controller: App\Controller\Admin\ManagementMealController::meal
adminContacts:
  path: /admin/contacts
  controller: App\Controller\Admin\ManagementContactsController::contacts
adminNewArticle:
  path: /admin/article/new
  controller: App\Controller\AdminEdit\ArticleController::newArticle
adminEditArticle:
  path: /admin/article/{id}/edit
  controller: App\Controller\AdminEdit\AdminEditController::editArticle
adminNewStore:
  path: /admin/store/new
  controller: App\Controller\AdminEdit\StoreController::newStore
adminEditStore:
  path: /admin/store/{id}/edit
  controller: App\Controller\AdminEdit\StoreController::editStore
adminNewRestaurant:
  path: /admin/restaurant/new
  controller: App\Controller\AdminEdit\RestaurantController::newRestaurant
adminEditRestaurant:
  path: /admin/restaurant/{id}/edit
  controller: App\Controller\AdminEdit\RestaurantController::editRestaurant
adminNewProduct:
  path: /admin/product/new
  controller: App\Controller\AdminEdit\ProductController::newProduct
adminEditProduct:
  path: /admin/product/{id}/edit
  controller: App\Controller\AdminEdit\ProductController::editProduct
adminNewMeal:
  path: /admin/meal/new
  controller: App\Controller\AdminEdit\MealController::newMeal
adminEditMeal:
  path: /admin/meal/{id}/edit
  controller: App\Controller\AdminEdit\MealController::editMeal
restaurantSearch:
  path: /restaurant/search
  controller: App\Controller\RestaurantController::restaurantSearch
storeSearch:
  path: /stores/search
  controller: App\Controller\StoreController::storeSearch
sendNoteRestaurant:
  path: /ajax/restaurant/sendNote
  controller: App\Controller\RestaurantController::sendNote
