#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
    path: /
    controller: App\Controller\IndexController::index
connexion:
    path: /connexion
    controller: App\Controller\ConnexionController::index
connexionAction:
    path: /ajax/connexionAction
    controller: App\Controller\ConnexionController::connexionAction
inscription:
    path: /inscription
    controller: App\Controller\InscriptionController::index
inscriptionAction:
    path: /ajax/inscriptionAction
    controller: App\Controller\InscriptionController::inscriptionAction
user:
    path: /user/{id}
    controller: App\Controller\UserController::index
article:
    path: /article
    controller: App\Controller\ArticleController::index
articleShow:
    path: /article/{id}
    controller: App\Controller\ArticleController::show
storeShow:
    path: /store/{id}
    controller: App\Controller\StoreController::show
contact:
    path: /contact
    controller: App\Controller\ContactController::index
contactSendMessage:
    path: /ajax/contact/sendMessage
    controller: App\Controller\ContactController::sendMessage
restaurants:
    path: /restaurants
    controller: App\Controller\RestaurantController::index
repas:
    path: /repas
    controller: App\Controller\RepasController::index
stores:
    path: /stores
    controller: App\Controller\StoreController::index
devenirVegetarien:
    path: /devenirvegetarien
    controller: App\Controller\DevenirVegetarienController::index
blog:
    path: /blog
    controller: App\Controller\BlogController::index
motDePasseOublie:
    path: /motdepasseoublie
    controller: App\Controller\MotDePasseOublieController::index
deconnexion:
    path: /deconnexion
    controller: App\Controller\ConnexionController::logout
admin:
    path: /admin
    controller: App\Controller\AdminController::index
adminGestionArticles:
    path: /admin/GestionArticles
    controller: App\Controller\AdminController::gestionArticles
adminGestionArticlesCommentaires:
    path: /admin/GestionArticlesCommentaires
    controller: App\Controller\AdminController::gestionArticlesCommentaires
adminGestionStores:
    path: /admin/GestionStores
    controller: App\Controller\AdminController::gestionStores
adminGestionProduitsStores:
    path: /admin/GestionProduitsStores
    controller: App\Controller\AdminController::gestionProduitsStores
adminGestionRestaurants:
    path: /admin/GestionRestaurants
    controller: App\Controller\AdminController::gestionRestaurants
adminGestionRestaurantsAvis:
    path: /admin/GestionRestaurantsAvis
    controller: App\Controller\AdminController::gestionRestaurantsAvis
adminProduits:
    path: /admin/produits
    controller: App\Controller\AdminController::produits
adminUtilisateurs:
    path: /admin/utilisateurs
    controller: App\Controller\AdminController::utilisateurs
adminRepas:
    path: /admin/repas
    controller: App\Controller\AdminController::repas
adminContacts:
    path: /admin/contacts
    controller: App\Controller\AdminController::contacts
adminNewArticle:
    path: /admin/article/new
    controller: App\Controller\AdminEditController::newArticle
adminEditArticle:
    path: /admin/article/{id}/edit
    controller: App\Controller\AdminEditController::editArticle
adminNewStore:
    path: /admin/store/new
    controller: App\Controller\AdminEditController::newStore
adminEditStore:
    path: /admin/store/{id}/edit
    controller: App\Controller\AdminEditController::editStore
adminNewRestaurant:
    path: /admin/restaurant/new
    controller: App\Controller\AdminEditController::newRestaurant
adminEditRestaurant:
    path: /admin/restaurant/{id}/edit
    controller: App\Controller\AdminEditController::editRestaurant
adminNewProduit:
    path: /admin/produit/new
    controller: App\Controller\AdminEditController::newProduit
adminEditProduit:
    path: /admin/produit/{id}/edit
    controller: App\Controller\AdminEditController::editProduit
adminNewRepas:
    path: /admin/repas/new
    controller: App\Controller\AdminEditController::newRepas
adminEditRepas:
    path: /admin/repas/{id}/edit
    controller: App\Controller\AdminEditController::editRepas
restaurantSearch:
    path: /restaurant/search
    controller: App\Controller\RestaurantController::restaurantSearch
storeSearch:
    path: /stores/search
    controller: App\Controller\StoreController::storeSearch
sendNoteRestaurant:
    path: /ajax/restaurant/sendNote
    controller: App\Controller\RestaurantController::sendNote