#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#testhj,kkj
index:
    path: /
    controller: App\Controller\IndexController::index
connexion:
    path: /connexion
    controller: App\Controller\ConnexionController::index
inscription:
    path: /inscription
    controller: App\Controller\InscriptionController::index
inscriptionAction:
    path: /ajax/inscriptionAction
    controller: App\Controller\InscriptionController::inscriptionAction
users:
    path: /users/{accountId}
    controller: App\Controller\UserController::index