#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
    path: /
    controller: App\Controller\IndexController::index
connexion:
    path: /connexion
    controller: App\Controller\ConnexionController::index
connexionAction:
    path: /ajax/connexionAction
    controller: App\Controller\ConnexionController::connexionAction
inscription:
    path: /inscription
    controller: App\Controller\InscriptionController::index
inscriptionAction:
    path: /ajax/inscriptionAction
    controller: App\Controller\InscriptionController::inscriptionAction
user:
    path: /user/{id}
    controller: App\Controller\UserController::index
article:
    path: /article
    controller: App\Controller\ArticleController::index
articleShow:
    path: /article/{id}
    controller: App\Controller\ArticleController::show
contact:
    path: /contact
    controller: App\Controller\ContactController::index
contactSendMessage:
    path: /ajax/contact/sendMessage
    controller: App\Controller\ContactController::sendMessage
restaurants:
    path: /restaurants
    controller: App\Controller\RestaurantController::index
magasins:
    path: /magasins
    controller: App\Controller\MagasinController::index
devenirVegetarien:
    path: /devenirvegetarien
    controller: App\Controller\DevenirVegetarienController::index
blog:
    path: /blog
    controller: App\Controller\BlogController::index
motDePasseOublie:
    path: /motdepasseoublie
    controller: App\Controller\MotDePasseOublieController::index
deconnexion:
    path: /deconnexion
    controller: App\Controller\ConnexionController::logout